### ISSUE TITLE
I try to apply the filter at the end of the description in the readme.md file, but it doesn't work.

### ISSUE THREAD

**Issue by wiedor** [kgusarov/spring-boot-netty#6]
First of all, I would like to thank you for releasing such a great source.

I try to apply the filter at the end of the description in the readme.md file, but it doesn't work.

![image](https://user-images.githubusercontent.com/17227497/124336852-bd498e80-dbda-11eb-938d-261057cebf85.png)

I wrote the code as it is in the documentation.

![image](https://user-images.githubusercontent.com/17227497/124336894-f71a9500-dbda-11eb-9227-11cc109ed74a.png)

size is returned as too large a value.

after in.readBytes(bytes,0,size); The system is dead in
The following logs are not recorded.

Which part is wrong?

Thank you.

**Comment by kgusarov** [comment]
Hi!

I see, that you've read first four bytes of message, that resolved to `825,373,492` in DEC. This is `3132 3334` in HEX. If we continue translating this further, I assume, that you were trying to send the message `1234....`. And this is where interesting part comes in. Netty is a low-level library. It won't prefix your message with its length, you have to do it yourself. 

In your case, can you provide the code, you were using to send the message. Or maybe you were using `telnet` or `nc` or any other tool? Then it would be a bit more complicated, because, you would have to implement more complex protocol to follow the example.
